version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/deployment
permissions:
  - object: /tmp/deployment
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
