version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - aws s3 sync . s3://wiegaaterkoffiehalen-static/ --exclude "*_Store" --exclude "video*" --exclude "sitemap.xml" --exclude "buildspec.yml" --exclude ".gitignore" --exclude ".git*" --delete
      - aws cloudfront create-invalidation --distribution-id E2X4WB5TYUPQN0 --paths "/*"
  post_build:
    commands:
      - echo Build completed on `date`
