version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - aws s3 sync . s3://wiegaaterkoffiehalen-static/ --exclude "*_Store" --exclude "video*" --exclude "sitemap.xml" --exclude "script*" --exclude appspec.yml --delete
  post_build:
    commands:
      - echo Build completed on `date`
